<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\AxisEngine.Assets\AxisEngine.Assets.csproj" />
    <ProjectReference Include="..\AxisEngine.Core\AxisEngine.Core.csproj" />
    <ProjectReference Include="..\AxisEngine.OpenGLBackend\AxisEngine.OpenGLBackend.csproj" />
  </ItemGroup>

</Project>
